run_name: gemma2_27b
num_runs: 1 # Increase this!
transformer_config:
  model_name: google/gemma-2-27b-it
  dtype: bfloat16
  cache_dir: /cache
  max_per_device_memory: 60GB
data_config:
  bucket_name: main
  data_key: web-instruct:CHAT_TEMPLATE
  n_batches: 150 # 250000
  seq_length: 2048
  batch_size: 4
  seed: 42
  skip_cache: False
  start_batch: 0 
  clean_added_tokens: True
  clean_default_system_prompt: True
upload_config:
  batches_per_upload: 32 
  hooks: [
    "models.layers.6.self_attn.pre", "models.layers.6.self_attn.post",
    "models.layers.6.mlp.pre", "models.layers.6.mlp.post",
    "models.layers.12.self_attn.pre", "models.layers.12.self_attn.post",
    "models.layers.12.mlp.pre", "models.layers.12.mlp.post",
    "models.layers.18.self_attn.pre", "models.layers.18.self_attn.post",
    "models.layers.18.mlp.pre", "models.layers.18.mlp.post",
    "models.layers.24.self_attn.pre", "models.layers.24.self_attn.post",
    "models.layers.24.mlp.pre", "models.layers.24.mlp.post"
  ]