run_name: gpt_oss_20b.edu-benchmark

transformer_config:
  model_name: openai/gpt-oss-20b
  dtype: bfloat16

data_config:
  data_key: alpaca-prompt-only:CHAT_TEMPLATE
  add_generation_prompt: true
  seq_length: 1024
  batch_size: 2
  n_batches: 16
  start_batch: 0
  skip_cache: False
  clean_added_tokens: true
  clean_default_system_prompt: true
  bucket_name: placeholder

upload_config:
  hooks:
    - models.layers.19.mlp.post
  batches_per_upload: 2
  storage_backend: disk
  local_output_dir: /tmp/activations

decode_config:
  enable: true
  max_new_tokens: 256
  temperature: 0.7
  top_p: 0.95
  stop_on_eos: true
  log_dir: decode_logs

num_runs: 1
machine_index: 0